const linkMap = {
    "image_116.png": "https://en.wikipedia.org/wiki/BNE_(artist)",
    "image_115.png": "https://www.instagram.com/sugascoop/",
    "image_114.png": "https://www.instagram.com/chrystienyc/?hl=ko",
    "image_113.png": "https://soundcloud.com/takt130",
    "image_112.png": "https://www.youtube.com/channel/UCHPs_itMF55uZOLkXk2HjUA",
    "image_108.png": "https://www.instagram.com/deepartment_store/",
    "image_106.png": "http://www.grone.kr/",
    "image_105.png": "https://soundcloud.com/takt130",
    "image_104.png": "https://www.instagram.com/arr_seoul/",
    "image_103.png": "https://arnoldparkstudios.com/",
    "image_102.png": "https://rdvz.kr/",
    "image_101.png": "https://www.instagram.com/hexter.90",
    "image_99.png": "https://www.instagram.com/carelesspress/",
    "image_98.png":
        "https://dtsq.bandcamp.com/album/moon-juice-and-space-biscuits",
    "image_97.png": "https://www.instagram.com/nanaisreal77/",
    "image_95.png": "https://www.instagram.com/stantonstreetsports/",
    "image_88.png": "https://www.instagram.com/hwzn.mfg.co/",
    "image_86.png": "https://www.instagram.com/akfeb.102/",
    "image_82.png": "https://www.instagram.com/thursdaybakery/",
    "image_81.png": "https://www.youtube.com/@vrlmv/",
    "image_78.png": "https://twitter.com/attention_god",
    "image_76.png": "http://www.grone.kr/",
    "image_73.png": "https://www.instagram.com/stance_seoul/",
    "image_72.png": "https://www.instagram.com/omacke/",
    "image_66.png": "https://lostmanagementcities.com/",
    "image_61.png": "https://www.youtube.com/watch?v=B-1U256bP9E",
    "image_60.png": "https://www.instagram.com/palpalskates/?hl=ko",
    "image_59.png": "https://www.fakemagazine.kr/",
    "image_54.png": "https://www.instagram.com/tipsy.seoul/",
    "image_53.png": "https://www.instagram.com/minnkan9/",
    "image_52.png": "https://www.instagram.com/hufworldwide",
    "image_48.png": "https://www.instagram.com/shma.plex",
    "image_45.png": "https://www.instagram.com/ruby.cherry.rose/",
    "image_44.png": "https://www.instagram.com/pulpbrewco/",
    "image_43.png": "https://www.instagram.com/nanaisreal77/",
    "image_42.png": "https://www.instagram.com/blank_mag/?hl=ko",
    "image_40.png": "https://www.youtube.com/watch?app=desktop&v=haWPp3XWKC0",
    "image_33.png": "https://www.instagram.com/pixie_ta/",
    "image_32.png": "https://www.instagram.com/wewastedyouth/",
    "image_28.png": "https://bundenko.com/",
    "image_22.png": "https://www.instagram.com/unit_form_collective",
    "image_20.png": "https://www.instagram.com/mosquitomurderers/",
    "image_19.png": "https://www.instagram.com/mega_junho",
    "image_18.png": "https://www.instagram.com/doezny/",
    "image_17.png": "https://www.instagram.com/21centuryhanliangsclub/",
    "image_15.png": "https://www.instagram.com/gnaaak_/",
    "image_13.png": "https://www.instagram.com/doyouknowminkwankim/",
    "image_12.png": "https://www.youtube.com/watch?v=sMc9PDKGYrs",
    "image_9.png": "https://www.mrkootattoo.com/",
    "image_8.png": "https://www.instagram.com/sano.1211111/",
    "image_4.png": "https://www.instagram.com/p/CtGsvPNpz-3/?hl=ko&img_index=1",
};

export default linkMap;
